# ----------------------------------
#Pterodactyl Core Dockerfile # Environment: ProjectZomboidServerEgg # Minimum Game Version: 41.xx 
# ----------------------------------
FROM ubuntu:22.04

MAINTAINER Shuazi233, <shuazi@ixovo.com>

ENV DEBIAN_FRONTEND noninteractive

RUN dpkg --add-architecture i386

RUN apt-get update

RUN apt-get install -y sudo dialog apt-utils locales

RUN locale-gen en_US.UTF-8
RUN locale-gen zh_CN.UTF-8
RUN locale-gen zh_CN.GBK

RUN sudo apt install -y curl wget file tar bzip2 gzip unzip bsdmainutils python3 util-linux ca-certificates binutils bc jq tmux netcat lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386 default-jre rng-tools tzdata telnet

RUN wget https://raw.githubusercontent.com/Shuazijun/ProjectZomboidEgg/main/entrypoint.sh -O /entrypoint.sh

RUN useradd -m -d /home/container container

USER container
ENV HOME=/home/container
WORKDIR /home/container
CMD ["/bin/bash", "/entrypoint.sh"]